### ISSUE TITLE
HikVision events in log but not passed as alerts 

### ISSUE THREAD

**Issue by h2009** [eu-evops/homebridge-hikvision#15]
Hello, I can see events from my cameras being registered however there is no notification (with the notifications turned on in HomeKit for the specific cameras). 

![8A039ED1-8B14-4442-9D85-FA7FAB5DDB14](https://user-images.githubusercontent.com/6642072/105255134-ed482c80-5b7a-11eb-8f71-03374ea20303.jpeg)
![Uploading 3B11C7F3-9BDF-49FE-9058-B787B8B634C5.jpeg…]()
![CAE90B7C-C82E-493D-B386-2B7F76277CEB](https://user-images.githubusercontent.com/6642072/105255204-0bae2800-5b7b-11eb-8ea4-c4f686430b58.jpeg)

**Comment by sponte** [comment]
Hi

This event is currently not propagated to Homekit. The only events that have been configured at the moment are:

```
     case "fielddetection":
      case "shelteralarm":
      case "VMD":
 ```

I'll add `linedetection` to the list and release a new version. Will try to look into it this week.

Feel free to submit PR for it :)

**Comment by sponte** [comment]
This should now be released in https://www.npmjs.com/package/@evops/homebridge-hikvision/v/1.0.14

**Comment by h2009** [comment]
Great thank you. I’ll let you know how I get on with this.
