### ISSUE TITLE
The requested platform 'Hikvision' was not registered by any plugin

### ISSUE THREAD

**Issue by al3x1337** [eu-evops/homebridge-hikvision#5]
![image](https://user-images.githubusercontent.com/44815197/97822738-d503f800-1c84-11eb-9ffc-69b11a2bd291.png)

Using Homebridge Config UI and have both homebridge-hikvision and homebridge-camera-ffmpeg installed. 
It works when setting up with just homebridge-camera-ffmpeg but when using homebridge-hikvision it throws me in the restart loop with this error.

Here is my config as per documentation. 

        {
            "platform": "Hikvision",
            "host": "192.168.1.91",
            "port": "80",
            "username": "admin",
            "password": "PASSWORD"
        },

**Comment by kravena** [comment]
Was getting the same error, performing the "npm install -g hap-nodejs" from the terminal window in the portal resolved that problem for me.

**Comment by al3x1337** [comment]
> 
> 
> Was getting the same error, performing the "npm install -g hap-nodejs" from the terminal window in the portal resolved that problem for me.
> 
> Because the hap-nodejs is not installed automatically, it's missing one of the dependencies and cannot load the Homebridge-Hikvision plugin, hence your error.

I went into terminal and installed it.

![image](https://user-images.githubusercontent.com/44815197/97904978-46888880-1d0f-11eb-9846-1f2af1800b39.png)

Using the same config as in my original post and after restarting HB and the container I still get the same error.

**Comment by kravena** [comment]
Ok, the two other things I did

1. I ran "sudo npm install -g hap-nodejs" from the terminal window
2. I installed the plug in "Homebridge Camera FFmpeg", as this plug in is based on it, but I never configured any of the options.

If the plugin is not loading, you will see it in the log, but much higher up and this is where I found Homebridge-Hikvision not loading due to a missing pre-req.

**Comment by al3x1337** [comment]
> 
> 
> Ok, the two other things I did
> 
>     1. I ran "sudo npm install -g hap-nodejs" from the terminal window
> 
>     2. I installed the plug in "Homebridge Camera FFmpeg", as this plug in is based on it, but I never configured any of the options.
> 
> 
> If the plugin is not loading, you will see it in the log, but much higher up and this is where I found Homebridge-Hikvision not loading due to a missing pre-req.

What ended up working is using  `npm install` and then `sudo npm i hap-nodejs`. One of those commands fixed it for me after having reinstalling hap-nodejs and the plugin not work, trying terminal through docker. 

Now I have a new error, same one  referenced in your Issue #6. 
![image](https://user-images.githubusercontent.com/44815197/97925798-fff75600-1d2f-11eb-9d1c-7b198f39731d.png)

- I have 6 cameras attached to my Hikvision NVR. 
- Have camera-ffmpeg installed, not configured
- camera-ffmpeg alone works and exposes my cameras so the rstp streams are correctly working 
- Check configuration and all information is correct; tried port 80 and 443

**Comment by al3x1337** [comment]
#6
